### ISSUE TITLE
Where to enable Admin permissions in apps.dev.microsoft.com or Azure

### ISSUE THREAD

**Issue by UHemarajU** [microsoftgraph/ios-objectiveC-snippets-sample#10]
Hi,

I had created a app in apps.dev.microsoft.com. There I had given permissions User.Read. My admin was given permission User.Read.All. Even that permission given by the admin why I am still getting error insufficient privileges or Need Admin Approval.

Can you explain me how to get all users data from the app created by User (non admin).?

Thank you.

**Comment by MIchaelMainer** [comment]
What API are you trying to call?

**Comment by UHemarajU** [comment]
MSGraph API. This is the query https://graph.microsoft.com/v1.0/users     ...Even my admin enabled the User.Read.All it asking Admin Consent.
