### ISSUE TITLE
ios 9.2 | swift 2.2 | build error

### ISSUE THREAD

**Issue by simula-r** [microsoftgraph/ios-objectiveC-snippets-sample#2]
I am receiving these errors when attempting to build the project

Type 'MSGraphClient' has no member 'defaultClient'

Value of type 'NXOAuth2AuthenticationProvider' has no member 'loginSilent'

I went back in scope and found that these members were never defined anywhere in the app.
I would love some guidance on this matter, thanks!

**Comment by unpluggedk** [comment]
Hello @JakeSchroeder 
Thanks for using the SDK.

Can you do a 'pod update' or even do a fresh 'pod install' after deleting the Podfile.lock and Pods folder and let us know the versions they are downloading?

In that, MSGraphSDK should be of 0.10.1, where MSGraphClient+DefaultConfiguration.h has the following for swift usage.
`+ (MSGraphClient*)client NS_SWIFT_NAME(defaultClient());`;

Also, MSGraphSDK-NXOAuth2Adapter should be of 0.9.2, where it has in NXOAuth2AuthenticationProvider a method
`- (BOOL) loginSilent;`

Thanks again!
