### ISSUE TITLE
not able to login with my organization account

### ISSUE THREAD

**Issue by Sravanik84** [microsoftgraph/ios-objectiveC-snippets-sample#8]
I am able to build and run the sample, however I am not able to login. After I enter my email id, it is saying 'We're taking to organization sign-in page'. however I have never seen the login page. I suppose this is problem with redirect url, however Im not sure where should i mention the redirect url. I am testing this on a simulator.

![simulator screen shot jan 12 2017 1 40 48 pm](https://cloud.githubusercontent.com/assets/9676912/21909485/0e4ce2b6-d8cd-11e6-8f5d-b9b6c6c15c72.png)

**Comment by jamescro** [comment]
Could you tell us some more about your environment? Are you working with a test O365 tenant? Are you using an on-prem ADFS tenant?

**Comment by Sravanik84** [comment]
I'm not sure if i understood your question correct. So I'm trying to login with my organization ADFS account. My ADFS account also have access to office 365. 

Also, my login with the other library (ADALiOS) is successful with same client id, from below git repo.
https://github.com/microsoftgraph/ios-objectivec-connect-rest-sample

**Comment by jamescro** [comment]
It might be the case that the NXOAuth2 library doesn't support your ADFS account. Is ADAL sufficient for your requirements?

**Comment by Sravanik84** [comment]
ADAL is good enough for obtaining an access token, however every time i send a rest call i have to validate for expired access token. NXOAuth2 provides great flexibility in regards with this, once we validate the account, the NXOAuth2 client will take care of your requests with using 'perform Method'. All I have to do is to provide the NXOAuth2 Client id and secret with redirect url.  So I was very hopeful this library(MSGraph with NXOath2 Adapter) would make things easier. 

I'm not sure what is meant by not supporting my ADFS account? If you provide me details about what kind of accounts are supported, I can check with my AD admin team.  

Well, my organization app is kind of dependent on this SDK and if it is not working, I have to write my own adapter classes for the NXOAuth2 client, though I'm not sure how far that would be successful.


Thanks

**Comment by jamescro** [comment]
Have you tried this on more than one machine? Sorry to keep asking questions, but I want to make sure that this isn't environmental.

**Comment by jamescro** [comment]
This other issue looks very similar to yours:
https://github.com/microsoftgraph/ios-swift-snippets-sample/issues/4
It appears that the NXOAuth2 client has issues with some ADFS setups, but I'm basing this assumption on just these two issues. Could you ask your AD admin team if there is anything unusual about your setup?

**Comment by Sravanik84** [comment]
I have not tried on other machine. 
With the same ADFS account & Client Id, I am able to obtain an access token,get response from the graph api from the same machine..

I can try asking my AD admin if there is anything unusual with my account, then he would ask me if there is anything wrong with my credentials (or not able to access something), which is not the case. I should be able to give him more details regarding what is that I need from my admin team. If you can tell me if there is any dependency for the sdk, from the organization set up (something like a server url/urn or redirect url if its specific for each organization) that would add more helpful.

**Comment by jamescro** [comment]
I will follow up with other stakeholders to see if we can provide a more specific debugging path.

**Comment by jamescro** [comment]
Before we go further, can you confirm that you haven't updated the redirect URI in the app registration portal? The library hardcodes the redirect URI value that you get by default when you register your app in the registration portal. (I'm referring to the portal here: https://apps.dev.microsoft.com.)
You should not have to change this value in your app registration, and you shouldn't have to set it in code. Doing either would break the authentication flow.

**Comment by unpluggedk** [comment]
Hey there, for your problem, you can actually use ADAL. 

You've stated "ADAL is good enough for obtaining an access token, however every time i send a rest call i have to validate for expired access token." and if that is the problem, there is a acquireTokenSilentWithResource call you can use. 

Just to clarify, this call will validate the token and if there is already a valid access token, it should not make a REST call.

**Comment by jamescro** [comment]
On a related point, it looks like the readme instructions are confusing things. Did you register your client id at the app registration portal (as noted in the Register and configure the app section) or at the Microsoft Graph App Registration Portal (as noted in the prerequsites section)? And if you used the Microsoft Graph App Registration Portal, did you go to the New app registration tool or to the old Office 365 registration tool). It could be that you're using a v1 auth client and attempting to do a v2 authentication flow.

**Comment by Sravanik84** [comment]
I did not provide/update any redirect URL in the app or in the registration portal.

Regarding app registration, currently the client id belongs to app which is registered on Azure portal. 
https://apps.dev.microsoft.com/

I have **not registered** for [an Office 365 Developer subscription ](https://profile.microsoft.com/RegSysProfileCenter/wizardnp.aspx?wizid=14b845d0-938c-45af-b061-f798fbb4d170&lcid=1033)

"And if you used the Microsoft Graph App Registration Portal, did you go to the New app registration tool or to the old Office 365 registration tool) " : I think it might be Office365 registration tool, as it is pointing to  the Azure portal.

If it helps, the app has the following api access:
<img width="584" alt="screen shot 2017-01-20 at 1 05 16 pm" src="https://cloud.githubusercontent.com/assets/9676912/22165537/36765e6c-df11-11e6-9991-97f5d5d2c930.png">

**Comment by jamescro** [comment]
Thanks. This probably doesn't have anything to do with your problem, but you don't need to assign those delegated permissions in the portal. The sample dynamically requests those scopes at runtime. 
And for what it's worth, it appears that you're using the adapter in a way that isn't necessarily supported:

"They refer to using NXOauth2Client to perform requests after authentication, frankly this is not a scenario I even looked at when designing the adapter as it did not fit into the SDK’s requestbuilder pattern. It may work, but YMMV – the ‘official’ way to perform requests is using the MSGraph SDK’s requestbuilder/request object model."

As Jason points out, ADAL supports silent token acquisition. Would that be sufficient?

**Comment by Sravanik84** [comment]
silent login to obtain access token will be good enough for my requirement. I am looking the sample code to use the Authentication context from the library, this might help.

**Comment by DianeD** [comment]
Hi @Sravanik84 . Thanks for the feedback! Please reopen this issue if you're still having problems.

**Comment by tapsbops** [comment]
@Sravanik84  I am experiencing the same problem did the silent login work ?
